version: "3"

services:
  cronicle:
    image: kaysar12/cronicle:1.0
    hostname: cronicle
    ports:
      - 3012:3012
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./conf:/opt/cronicle/conf
      - ./data:/opt/cronicle/data
      - ./logs:/opt/cronicle/logs
      - ./plugins:/opt/cronicle/plugins
    entrypoint: /setup/docker-entrypoint.sh
    environment:
      IS_MASTER: "1"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:3012/api/app/ping || exit 1" ]
      interval: 5s
      timeout: 1s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  cronicle-worker:
    image: kaysar12/cronicle:1.0
    hostname: cronicle-worker
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./conf:/opt/cronicle/conf
    entrypoint: /setup/docker-entrypoint.sh
    environment:
      IS_MASTER: "0"
    depends_on:
      - cronicle
  cronicle-worker2:
    image: kaysar12/cronicle:1.0
    hostname: cronicle-worker2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./conf:/opt/cronicle/conf
    entrypoint: /setup/docker-entrypoint.sh
    environment:
      IS_MASTER: "0"
    depends_on:
      - cronicle
